local:
  hosts:
    192.168.215.2:
    192.168.215.3:

node1:
  hosts:
    192.168.215.2:
  vars:
    ansible_user: admin

node2:
  hosts:
    192.168.215.3:
  vars:
    ansible_user: admin

nodes:
  children:
    node1:
    node2:
